name=AQM1602_SoftI2C
version=1.0.0
author=asa-lab-bit
maintainer=asa-lab-bit
sentence=Lightweight AQM1602 LCD library using SoftI2C
paragraph=No Wire library required. Works on ATtiny with small memory footprint.
category=Display
url=https://github.com/asa-lab-bit/AQM1602_SoftI2C
architectures=*
